### ISSUE TITLE
git missing in container

### ISSUE THREAD

**Issue by lazyzero** [sglahn/docker-platformio-core#10]
Hello @sglahn,

I am using your docker image from dockerhub for actions on github. In a new project I have to use git for some dependencies e.g. my lib_deps has tehe following line: 
 Adafruit GFX Library=https://github.com/adafruit/Adafruit-GFX-Library.git#1.3.6

can you please add a apt-get install git && apt clean to the Dockerfile?

Thanks Christian

**Comment by sglahn** [comment]
I have merged your PR containing git.
